pipeline{
    agent{
        label 'docker-agent'
    }
    stages{
        stage('checkout scm'){
            steps{checkout scm}
        }
        stage('Deploy Environment'){
            steps{
                sh 'docker compose -f deploy/docker-compose.yml up -d --build'
                sleep 5
            }
        }
        stage('Test container'){
            steps{
                sh 'curl http://api:8080 || curl http://localhost:8080'
            }
        }
    }
    post {
        always{
            sh 'docker compose -f deploy/docker-compose.yml down'
        }
        success{
            sh 'echo TASK EXECUTED SUCCESSFULLY' 
        }
        failure{
            sh 'echo TASK FAILED'
        }
    }
}